export const data = {
  products: [
    {
      id: '1',
      name: 'Dinossauro',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '2',
      name: 'Ursinho',
      image: '/images/p2.jpg',
      price: 70,
      countInStock: 1,
      rating: 4.0,
      numReviews: 10,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '3',
      name: 'Bailarina',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 1,
      rating: 4.5,
      numReviews: 14,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '4',
      name: 'Batman',
      image: '/images/p4.jpg',
      price: 140,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '5',
      name: 'Centopeia',
      image: '/images/p5.jpg',
      price: 110,
      countInStock: 5,
      rating: 4.5,
      numReviews: 8,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '6',
      name: 'Ariel',
      image: '/images/p6.jpg',
      price: 140,
      countInStock: 0,
      rating: 5,
      numReviews: 12,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '7',
      name: 'Gato Bruxo',
      image: '/images/p7.jpg',
      price: 80,
      countInStock: 1,
      rating: 4.5,
      numReviews: 5,
      description: 'Amigurumi feito com material anti-alergico',
    },
    {
      id: '8',
      name: 'Harry Potter',
      image: '/images/p8.jpg',
      price: 100,
      countInStock: 1,
      rating: 4,
      numReviews: 20,
      description: 'Amigurumi feito com material anti-alergico',
    },
  ],
};
